// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/deco/analytics.ts";
import * as $$$$$$$$$$$1 from "./apps/deco/konfidency.ts";
import * as $$$$$$$$$$$2 from "./apps/deco/wake.ts";
import * as $$$$$$$$$$$3 from "./apps/deco/weather.ts";
import * as $$$$$$$$$$$4 from "./apps/deco/workflows.ts";
import * as $$$$$$$$$$$5 from "./apps/site.ts";
import * as $$$9 from "./loaders/adKevel.ts";
import * as $$$10 from "./loaders/availableIcons.ts";
import * as $$$0 from "./loaders/CepPriceLoader.ts";
import * as $$$1 from "./loaders/CepValidator.ts";
import * as $$$11 from "./loaders/checkoutMetadataVariant.ts";
import * as $$$2 from "./loaders/ContentProductPage.ts";
import * as $$$12 from "./loaders/getProduct.ts";
import * as $$$13 from "./loaders/getProductOnly.ts";
import * as $$$14 from "./loaders/home.ts";
import * as $$$15 from "./loaders/icons.ts";
import * as $$$3 from "./loaders/Konfidency.ts";
import * as $$$4 from "./loaders/Layouts/ProductCard.tsx";
import * as $$$5 from "./loaders/List/Sections.tsx";
import * as $$$6 from "./loaders/ListingFromAtoZ.ts";
import * as $$$16 from "./loaders/partenerByCoordinates.ts";
import * as $$$17 from "./loaders/productDetailsLeafllet.ts";
import * as $$$18 from "./loaders/productDetailsPage.ts";
import * as $$$19 from "./loaders/productList.ts";
import * as $$$22 from "./loaders/productListingPage.ts";
import * as $$$23 from "./loaders/productListingPageAtributesBrand.ts";
import * as $$$24 from "./loaders/productListingPageAtributesDisease.ts";
import * as $$$25 from "./loaders/productListingPageAtributesSeller.ts";
import * as $$$26 from "./loaders/productListingPageAtributesSubstance.ts";
import * as $$$27 from "./loaders/productListingPageFactory.ts";
import * as $$$20 from "./loaders/productListRecommendation.ts";
import * as $$$21 from "./loaders/productListWishlist.ts";
import * as $$$7 from "./loaders/ProductLoader.ts";
import * as $$$28 from "./loaders/productOffers.ts";
import * as $$$8 from "./loaders/Redirects.ts";
import * as $$$29 from "./loaders/singlePageFromAtoZBrand.ts";
import * as $$$30 from "./loaders/singlePageFromAtoZDisease.ts";
import * as $$$34 from "./loaders/singlePageFromAtoZfactory.ts";
import * as $$$31 from "./loaders/singlePageFromAtoZMedicine.ts";
import * as $$$32 from "./loaders/singlePageFromAtoZSubstance.ts";
import * as $$$33 from "./loaders/singlePageFromAtoZTherapeuticClass.ts";
import * as $$$35 from "./loaders/suggestion.ts";
import * as $$$36 from "./loaders/user.ts";
import * as $$$37 from "./loaders/wishlist.ts";
import * as $$$38 from "./loaders/wishlistRemoveItem.ts";
import * as $$$$$$100 from "./sections/aboutUs/BlockInfo.tsx";
import * as $$$$$$101 from "./sections/aboutUs/DownText.tsx";
import * as $$$$$$102 from "./sections/aboutUs/ImageAboutUs.tsx";
import * as $$$$$$103 from "./sections/aboutUs/InfoSection.tsx";
import * as $$$$$$104 from "./sections/aboutUs/NavItemsAboutUs.tsx";
import * as $$$$$$105 from "./sections/aboutUs/TextAboutUs.tsx";
import * as $$$$$$106 from "./sections/aboutUs/TopText.tsx";
import * as $$$$$$0 from "./sections/Animation/Animation.tsx";
import * as $$$$$$1 from "./sections/Banners/Banner.tsx";
import * as $$$$$$2 from "./sections/Banners/BannerSlider.tsx";
import * as $$$$$$3 from "./sections/Banners/BannerSliderKevel.tsx";
import * as $$$$$$4 from "./sections/Cards/IconCardsCarousel.tsx";
import * as $$$$$$5 from "./sections/Cards/IconCardsCarouselWithImage.tsx";
import * as $$$$$$6 from "./sections/Cards/ImageCardsCarousel.tsx";
import * as $$$$$$7 from "./sections/Cards/ImageCardsCarouselWithImage.tsx";
import * as $$$$$$8 from "./sections/Category/CategoryAZ.tsx";
import * as $$$$$$9 from "./sections/Category/CategoryBanner.tsx";
import * as $$$$$$10 from "./sections/Category/CategoryGrid.tsx";
import * as $$$$$$11 from "./sections/Category/CategoryList.tsx";
import * as $$$$$$12 from "./sections/Category/CategoyPageList.tsx";
import * as $$$$$$13 from "./sections/Content/Benefits.tsx";
import * as $$$$$$14 from "./sections/Content/BlogPosts.tsx";
import * as $$$$$$15 from "./sections/Content/CallToAction.tsx";
import * as $$$$$$16 from "./sections/Content/Faq.tsx";
import * as $$$$$$17 from "./sections/Content/Features.tsx";
import * as $$$$$$18 from "./sections/Content/Hero.tsx";
import * as $$$$$$19 from "./sections/Content/ImageSection.tsx";
import * as $$$$$$20 from "./sections/Content/Intro.tsx";
import * as $$$$$$21 from "./sections/Content/Logos.tsx";
import * as $$$$$$22 from "./sections/Content/Partners.tsx";
import * as $$$$$$23 from "./sections/Content/PopUpPrivacyPolicy.tsx";
import * as $$$$$$24 from "./sections/Content/RichText.tsx";
import * as $$$$$$25 from "./sections/Content/Table.tsx";
import * as $$$$$$26 from "./sections/Content/Testimonials.tsx";
import * as $$$$$$27 from "./sections/Content/TextWithImage.tsx";
import * as $$$$$$28 from "./sections/Content/titleH1.tsx";
import * as $$$$$$29 from "./sections/Editorial/BreadCrumAndInfos.tsx";
import * as $$$$$$30 from "./sections/Editorial/BreadCrumbInstitucional.tsx";
import * as $$$$$$31 from "./sections/Footer.tsx";
import * as $$$$$$32 from "./sections/Footer/EvaluationSection.tsx";
import * as $$$$$$33 from "./sections/Footer/Footer.tsx";
import * as $$$$$$34 from "./sections/Footer/FooterMain.tsx";
import * as $$$$$$35 from "./sections/Gallery.tsx";
import * as $$$$$$36 from "./sections/Header/Header.tsx";
import * as $$$$$$37 from "./sections/Images/BannerGrid.tsx";
import * as $$$$$$38 from "./sections/Images/Carousel.tsx";
import * as $$$$$$39 from "./sections/Images/ImageGallery.tsx";
import * as $$$$$$40 from "./sections/Images/ShoppableBanner.tsx";
import * as $$$$$$41 from "./sections/ItWorks.tsx";
import * as $$$$$$42 from "./sections/Links/LinkTree.tsx";
import * as $$$$$$43 from "./sections/Links/Shortcuts.tsx";
import * as $$$$$$44 from "./sections/ListingFromAtoZ/ContentTop.tsx";
import * as $$$$$$45 from "./sections/ListingFromAtoZ/ListingFromAtoDisease.tsx";
import * as $$$$$$52 from "./sections/ListingFromAtoZ/ListingFromAtoZbrand.tsx";
import * as $$$$$$53 from "./sections/ListingFromAtoZ/ListingFromAtoZfactory.tsx";
import * as $$$$$$46 from "./sections/ListingFromAtoZ/ListingFromAtoZGeneric.tsx";
import * as $$$$$$47 from "./sections/ListingFromAtoZ/ListingFromAtoZLeaflet.tsx";
import * as $$$$$$48 from "./sections/ListingFromAtoZ/ListingFromAtoZMedicationReferences.tsx";
import * as $$$$$$49 from "./sections/ListingFromAtoZ/ListingFromAtoZMedicine.tsx";
import * as $$$$$$50 from "./sections/ListingFromAtoZ/ListingFromAtoZSubstance.tsx";
import * as $$$$$$51 from "./sections/ListingFromAtoZ/ListingFromAtoZTherapeuticClass.tsx";
import * as $$$$$$54 from "./sections/ListingFromAtoZ/singlePageBrand.tsx";
import * as $$$$$$55 from "./sections/ListingFromAtoZ/singlePageDisease.tsx";
import * as $$$$$$56 from "./sections/ListingFromAtoZ/singlePageFactory.tsx";
import * as $$$$$$57 from "./sections/ListingFromAtoZ/singlePageGeneric.tsx";
import * as $$$$$$58 from "./sections/ListingFromAtoZ/singlePageLeaflet.tsx";
import * as $$$$$$59 from "./sections/ListingFromAtoZ/singlePageMedicationReferences.tsx";
import * as $$$$$$60 from "./sections/ListingFromAtoZ/singlePageMedicine.tsx";
import * as $$$$$$61 from "./sections/ListingFromAtoZ/singlePageSubstance.tsx";
import * as $$$$$$62 from "./sections/ListingFromAtoZ/singlePageTherapeuticClass.tsx";
import * as $$$$$$63 from "./sections/Miscellaneous/CampaignTimer.tsx";
import * as $$$$$$64 from "./sections/Miscellaneous/CookieConsent.tsx";
import * as $$$$$$65 from "./sections/Miscellaneous/Slide.tsx";
import * as $$$$$$66 from "./sections/Newsletter/Newsletter.tsx";
import * as $$$$$$67 from "./sections/Product/ContentProductMainPage.tsx";
import * as $$$$$$68 from "./sections/Product/ContentProductPage.tsx";
import * as $$$$$$69 from "./sections/Product/ImageGalleryFrontBack.tsx";
import * as $$$$$$70 from "./sections/Product/Konfidency.tsx";
import * as $$$$$$71 from "./sections/Product/NotFound.tsx";
import * as $$$$$$72 from "./sections/Product/NotFoundChallenge.tsx";
import * as $$$$$$73 from "./sections/Product/ProductDetails.tsx";
import * as $$$$$$74 from "./sections/Product/ProductDetailsLeaflet.tsx";
import * as $$$$$$75 from "./sections/Product/ProductDetailsMain.tsx";
import * as $$$$$$76 from "./sections/Product/ProductShelf.tsx";
import * as $$$$$$77 from "./sections/Product/ProductShelfHome.tsx";
import * as $$$$$$78 from "./sections/Product/ProductShelfRecommendation.tsx";
import * as $$$$$$79 from "./sections/Product/ProductShelfTabbed.tsx";
import * as $$$$$$80 from "./sections/Product/ProductShelfWishlist.tsx";
import * as $$$$$$81 from "./sections/Product/RecentlyAddedProducts.tsx";
import * as $$$$$$82 from "./sections/Product/RelatedProductsSection.tsx";
import * as $$$$$$83 from "./sections/Product/SearchResult.tsx";
import * as $$$$$$84 from "./sections/Product/ShelfWithImage.tsx";
import * as $$$$$$85 from "./sections/Product/Wishlist.tsx";
import * as $$$$$$86 from "./sections/SEO/ProductDataHome.tsx";
import * as $$$$$$87 from "./sections/SEO/ProductDataLeaflet.tsx";
import * as $$$$$$88 from "./sections/SEO/ProductDataProductMain.tsx";
import * as $$$$$$89 from "./sections/SEO/ProductDataProductVariant.tsx";
import * as $$$$$$90 from "./sections/SEO/SeoLeaflet.tsx";
import * as $$$$$$91 from "./sections/SEO/SeoPLPV2.tsx";
import * as $$$$$$92 from "./sections/SEO/SeoProductPDP.tsx";
import * as $$$$$$94 from "./sections/SEO/SeoV2general.tsx";
import * as $$$$$$93 from "./sections/SEO/SeoV2ListToAaZ.tsx";
import * as $$$$$$95 from "./sections/SEO/SeoVariantionPDP.tsx";
import * as $$$$$$96 from "./sections/Social/InstagramPosts.tsx";
import * as $$$$$$97 from "./sections/Social/WhatsApp.tsx";
import * as $$$$$$98 from "./sections/TermosPoliticas/content.tsx";
import * as $$$$$$99 from "./sections/Theme/Theme.tsx";

const manifest = {
  "loaders": {
    "site/loaders/adKevel.ts": $$$9,
    "site/loaders/availableIcons.ts": $$$10,
    "site/loaders/CepPriceLoader.ts": $$$0,
    "site/loaders/CepValidator.ts": $$$1,
    "site/loaders/checkoutMetadataVariant.ts": $$$11,
    "site/loaders/ContentProductPage.ts": $$$2,
    "site/loaders/getProduct.ts": $$$12,
    "site/loaders/getProductOnly.ts": $$$13,
    "site/loaders/home.ts": $$$14,
    "site/loaders/icons.ts": $$$15,
    "site/loaders/Konfidency.ts": $$$3,
    "site/loaders/Layouts/ProductCard.tsx": $$$4,
    "site/loaders/List/Sections.tsx": $$$5,
    "site/loaders/ListingFromAtoZ.ts": $$$6,
    "site/loaders/partenerByCoordinates.ts": $$$16,
    "site/loaders/productDetailsLeafllet.ts": $$$17,
    "site/loaders/productDetailsPage.ts": $$$18,
    "site/loaders/productList.ts": $$$19,
    "site/loaders/productListingPage.ts": $$$22,
    "site/loaders/productListingPageAtributesBrand.ts": $$$23,
    "site/loaders/productListingPageAtributesDisease.ts": $$$24,
    "site/loaders/productListingPageAtributesSeller.ts": $$$25,
    "site/loaders/productListingPageAtributesSubstance.ts": $$$26,
    "site/loaders/productListingPageFactory.ts": $$$27,
    "site/loaders/productListRecommendation.ts": $$$20,
    "site/loaders/productListWishlist.ts": $$$21,
    "site/loaders/ProductLoader.ts": $$$7,
    "site/loaders/productOffers.ts": $$$28,
    "site/loaders/Redirects.ts": $$$8,
    "site/loaders/singlePageFromAtoZBrand.ts": $$$29,
    "site/loaders/singlePageFromAtoZDisease.ts": $$$30,
    "site/loaders/singlePageFromAtoZfactory.ts": $$$34,
    "site/loaders/singlePageFromAtoZMedicine.ts": $$$31,
    "site/loaders/singlePageFromAtoZSubstance.ts": $$$32,
    "site/loaders/singlePageFromAtoZTherapeuticClass.ts": $$$33,
    "site/loaders/suggestion.ts": $$$35,
    "site/loaders/user.ts": $$$36,
    "site/loaders/wishlist.ts": $$$37,
    "site/loaders/wishlistRemoveItem.ts": $$$38,
  },
  "sections": {
    "site/sections/aboutUs/BlockInfo.tsx": $$$$$$100,
    "site/sections/aboutUs/DownText.tsx": $$$$$$101,
    "site/sections/aboutUs/ImageAboutUs.tsx": $$$$$$102,
    "site/sections/aboutUs/InfoSection.tsx": $$$$$$103,
    "site/sections/aboutUs/NavItemsAboutUs.tsx": $$$$$$104,
    "site/sections/aboutUs/TextAboutUs.tsx": $$$$$$105,
    "site/sections/aboutUs/TopText.tsx": $$$$$$106,
    "site/sections/Animation/Animation.tsx": $$$$$$0,
    "site/sections/Banners/Banner.tsx": $$$$$$1,
    "site/sections/Banners/BannerSlider.tsx": $$$$$$2,
    "site/sections/Banners/BannerSliderKevel.tsx": $$$$$$3,
    "site/sections/Cards/IconCardsCarousel.tsx": $$$$$$4,
    "site/sections/Cards/IconCardsCarouselWithImage.tsx": $$$$$$5,
    "site/sections/Cards/ImageCardsCarousel.tsx": $$$$$$6,
    "site/sections/Cards/ImageCardsCarouselWithImage.tsx": $$$$$$7,
    "site/sections/Category/CategoryAZ.tsx": $$$$$$8,
    "site/sections/Category/CategoryBanner.tsx": $$$$$$9,
    "site/sections/Category/CategoryGrid.tsx": $$$$$$10,
    "site/sections/Category/CategoryList.tsx": $$$$$$11,
    "site/sections/Category/CategoyPageList.tsx": $$$$$$12,
    "site/sections/Content/Benefits.tsx": $$$$$$13,
    "site/sections/Content/BlogPosts.tsx": $$$$$$14,
    "site/sections/Content/CallToAction.tsx": $$$$$$15,
    "site/sections/Content/Faq.tsx": $$$$$$16,
    "site/sections/Content/Features.tsx": $$$$$$17,
    "site/sections/Content/Hero.tsx": $$$$$$18,
    "site/sections/Content/ImageSection.tsx": $$$$$$19,
    "site/sections/Content/Intro.tsx": $$$$$$20,
    "site/sections/Content/Logos.tsx": $$$$$$21,
    "site/sections/Content/Partners.tsx": $$$$$$22,
    "site/sections/Content/PopUpPrivacyPolicy.tsx": $$$$$$23,
    "site/sections/Content/RichText.tsx": $$$$$$24,
    "site/sections/Content/Table.tsx": $$$$$$25,
    "site/sections/Content/Testimonials.tsx": $$$$$$26,
    "site/sections/Content/TextWithImage.tsx": $$$$$$27,
    "site/sections/Content/titleH1.tsx": $$$$$$28,
    "site/sections/Editorial/BreadCrumAndInfos.tsx": $$$$$$29,
    "site/sections/Editorial/BreadCrumbInstitucional.tsx": $$$$$$30,
    "site/sections/Footer.tsx": $$$$$$31,
    "site/sections/Footer/EvaluationSection.tsx": $$$$$$32,
    "site/sections/Footer/Footer.tsx": $$$$$$33,
    "site/sections/Footer/FooterMain.tsx": $$$$$$34,
    "site/sections/Gallery.tsx": $$$$$$35,
    "site/sections/Header/Header.tsx": $$$$$$36,
    "site/sections/Images/BannerGrid.tsx": $$$$$$37,
    "site/sections/Images/Carousel.tsx": $$$$$$38,
    "site/sections/Images/ImageGallery.tsx": $$$$$$39,
    "site/sections/Images/ShoppableBanner.tsx": $$$$$$40,
    "site/sections/ItWorks.tsx": $$$$$$41,
    "site/sections/Links/LinkTree.tsx": $$$$$$42,
    "site/sections/Links/Shortcuts.tsx": $$$$$$43,
    "site/sections/ListingFromAtoZ/ContentTop.tsx": $$$$$$44,
    "site/sections/ListingFromAtoZ/ListingFromAtoDisease.tsx": $$$$$$45,
    "site/sections/ListingFromAtoZ/ListingFromAtoZbrand.tsx": $$$$$$52,
    "site/sections/ListingFromAtoZ/ListingFromAtoZfactory.tsx": $$$$$$53,
    "site/sections/ListingFromAtoZ/ListingFromAtoZGeneric.tsx": $$$$$$46,
    "site/sections/ListingFromAtoZ/ListingFromAtoZLeaflet.tsx": $$$$$$47,
    "site/sections/ListingFromAtoZ/ListingFromAtoZMedicationReferences.tsx":
      $$$$$$48,
    "site/sections/ListingFromAtoZ/ListingFromAtoZMedicine.tsx": $$$$$$49,
    "site/sections/ListingFromAtoZ/ListingFromAtoZSubstance.tsx": $$$$$$50,
    "site/sections/ListingFromAtoZ/ListingFromAtoZTherapeuticClass.tsx":
      $$$$$$51,
    "site/sections/ListingFromAtoZ/singlePageBrand.tsx": $$$$$$54,
    "site/sections/ListingFromAtoZ/singlePageDisease.tsx": $$$$$$55,
    "site/sections/ListingFromAtoZ/singlePageFactory.tsx": $$$$$$56,
    "site/sections/ListingFromAtoZ/singlePageGeneric.tsx": $$$$$$57,
    "site/sections/ListingFromAtoZ/singlePageLeaflet.tsx": $$$$$$58,
    "site/sections/ListingFromAtoZ/singlePageMedicationReferences.tsx":
      $$$$$$59,
    "site/sections/ListingFromAtoZ/singlePageMedicine.tsx": $$$$$$60,
    "site/sections/ListingFromAtoZ/singlePageSubstance.tsx": $$$$$$61,
    "site/sections/ListingFromAtoZ/singlePageTherapeuticClass.tsx": $$$$$$62,
    "site/sections/Miscellaneous/CampaignTimer.tsx": $$$$$$63,
    "site/sections/Miscellaneous/CookieConsent.tsx": $$$$$$64,
    "site/sections/Miscellaneous/Slide.tsx": $$$$$$65,
    "site/sections/Newsletter/Newsletter.tsx": $$$$$$66,
    "site/sections/Product/ContentProductMainPage.tsx": $$$$$$67,
    "site/sections/Product/ContentProductPage.tsx": $$$$$$68,
    "site/sections/Product/ImageGalleryFrontBack.tsx": $$$$$$69,
    "site/sections/Product/Konfidency.tsx": $$$$$$70,
    "site/sections/Product/NotFound.tsx": $$$$$$71,
    "site/sections/Product/NotFoundChallenge.tsx": $$$$$$72,
    "site/sections/Product/ProductDetails.tsx": $$$$$$73,
    "site/sections/Product/ProductDetailsLeaflet.tsx": $$$$$$74,
    "site/sections/Product/ProductDetailsMain.tsx": $$$$$$75,
    "site/sections/Product/ProductShelf.tsx": $$$$$$76,
    "site/sections/Product/ProductShelfHome.tsx": $$$$$$77,
    "site/sections/Product/ProductShelfRecommendation.tsx": $$$$$$78,
    "site/sections/Product/ProductShelfTabbed.tsx": $$$$$$79,
    "site/sections/Product/ProductShelfWishlist.tsx": $$$$$$80,
    "site/sections/Product/RecentlyAddedProducts.tsx": $$$$$$81,
    "site/sections/Product/RelatedProductsSection.tsx": $$$$$$82,
    "site/sections/Product/SearchResult.tsx": $$$$$$83,
    "site/sections/Product/ShelfWithImage.tsx": $$$$$$84,
    "site/sections/Product/Wishlist.tsx": $$$$$$85,
    "site/sections/SEO/ProductDataHome.tsx": $$$$$$86,
    "site/sections/SEO/ProductDataLeaflet.tsx": $$$$$$87,
    "site/sections/SEO/ProductDataProductMain.tsx": $$$$$$88,
    "site/sections/SEO/ProductDataProductVariant.tsx": $$$$$$89,
    "site/sections/SEO/SeoLeaflet.tsx": $$$$$$90,
    "site/sections/SEO/SeoPLPV2.tsx": $$$$$$91,
    "site/sections/SEO/SeoProductPDP.tsx": $$$$$$92,
    "site/sections/SEO/SeoV2general.tsx": $$$$$$94,
    "site/sections/SEO/SeoV2ListToAaZ.tsx": $$$$$$93,
    "site/sections/SEO/SeoVariantionPDP.tsx": $$$$$$95,
    "site/sections/Social/InstagramPosts.tsx": $$$$$$96,
    "site/sections/Social/WhatsApp.tsx": $$$$$$97,
    "site/sections/TermosPoliticas/content.tsx": $$$$$$98,
    "site/sections/Theme/Theme.tsx": $$$$$$99,
  },
  "apps": {
    "site/apps/deco/analytics.ts": $$$$$$$$$$$0,
    "site/apps/deco/konfidency.ts": $$$$$$$$$$$1,
    "site/apps/deco/wake.ts": $$$$$$$$$$$2,
    "site/apps/deco/weather.ts": $$$$$$$$$$$3,
    "site/apps/deco/workflows.ts": $$$$$$$$$$$4,
    "site/apps/site.ts": $$$$$$$$$$$5,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
