name: Build and Push Docker Image to GCP

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      REGISTRY: ${{ secrets.REGISTRY_LOGIN_SERVER }}
      IMAGE_NAME: consulta-remedio  # change this to your image name

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate timestamp
        id: timestamp
        run: echo "tag=$(date -u +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker login to Azure Container Registry
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login "${{ secrets.REGISTRY_LOGIN_SERVER }}" \
            --username "${{ secrets.ACR_USERNAME }}" \
            --password-stdin

      - name: Get short SHA
        id: vars
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        
      - name: Build and Push with Cache
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.short_sha }}
          build-args: |
            GIT_REVISION=${{ steps.vars.outputs.short_sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
